# Generated by Django 3.2.3 on 2021-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('Pack_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название пака:')),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('Ques_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('question_text', models.CharField(max_length=200, null=True, verbose_name='Вопрос:')),
            ],
        ),
        migrations.CreateModel(
            name='PaQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pack', models.ManyToManyField(to='packages.Package')),
                ('Quest', models.ManyToManyField(to='packages.Ques')),
            ],
        ),
    ]
